volumes:
  wine-data:
    external: true
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    environment:
      SIGNING_KEY: 9745929A1A9BE1BC97C58788B6FCF
      FOOD_API_KEY: 741|bWA4puvyfVY3JmRH65jH9hca1WkjH5Z3ijQPl5qh
      DATABASE_URL: postgresql://wines_user:wines@db/wines
      WAIT_HOST: db:5432
      PORT: 8000
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi/app:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_WINES_API_HOST: http://localhost:8000
      REACT_APP_WS_HOST: ws://127.0.0.1:8000
  db:
    image: postgres:14.5-bullseye
    volumes:
      - wine-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: wines
      POSTGRES_USER: wines_user
      POSTGRES_DB: wines
    ports:
      - "15432:5432"
